packageName: konveyor-operator
channels:
- name: latest
  currentCSV: konveyor-operator.latest
- name: release-v1.1
  currentCSV: konveyor-operator.v1.1.1
- name: release-v1
  currentCSV: konveyor-operator.v1.0.1
defaultChannel: release-v1.1
