packageName: konveyor-operator
channels:
- name: latest
  currentCSV: konveyor-operator.v99.0.0
- name: release-v1.2
  currentCSV: konveyor-operator.v1.2.4
- name: release-v1.1
  currentCSV: konveyor-operator.v1.1.2
defaultChannel: release-v1.2
