---
azure_resource_group: ""
configmap_secret: ""
controller_state: absent
deprecated_cors_configuration: false
cors_origins: []
disable_image_migration: false
disable_pv_migration: false
excluded_resources:
  - imagetags
  - templateinstances
  - clusterserviceversions
  - packagemanifests
  - subscriptions
  - servicebrokers
  - servicebindings
  - serviceclasses
  - serviceinstances
  - serviceplans
  - operatorgroups
  - events
proxy_secret_name: "migration-proxy"
http_proxy: "{{ lookup( 'env', 'HTTP_PROXY') }}"
https_proxy: "{{ lookup( 'env', 'HTTPS_PROXY') }}"
no_proxy: "{{ lookup( 'env', 'NO_PROXY') }}"
image_pull_policy: Always
hook_runner_image: "{{ registry }}/{{ project }}/{{ hook_runner_repo }}"
hook_runner_repo: "{{ lookup( 'env', 'HOOK_RUNNER_REPO') }}"
hook_runner_version: "{{ snapshot_tag | default(lookup( 'env', 'HOOK_RUNNER_TAG')) }}"
hook_runner_image_fqin: "{{ hook_runner_image }}:{{ hook_runner_version }}"
mig_controller_image: "{{ registry }}/{{ project }}/{{ mig_controller_repo }}"
mig_controller_limits_cpu: "1"
mig_controller_limits_memory: "10Gi"
mig_controller_repo: "{{ lookup( 'env', 'MIG_CONTROLLER_REPO') }}"
mig_controller_requests_cpu: "100m"
mig_controller_requests_memory: "350Mi"
mig_controller_version: "{{ snapshot_tag | default(lookup( 'env', 'MIG_CONTROLLER_TAG')) }}"
mig_controller_image_fqin: "{{ mig_controller_image }}:{{ mig_controller_version }}"
discovery_volume_path: "/var/cache/discovery"
mig_pv_limit: "100"
mig_pod_limit: "100"
mig_namespace_limit: "10"
mig_namespace: "{{ lookup( 'env', 'WATCH_NAMESPACE') | default('openshift-migration') }}"
mig_ui_cluster_api_endpoint: ""
mig_ui_configmap_data: ""
mig_ui_configmap_name: mig-ui-config
mig_ui_config_namespace: openshift-migration
mig_ui_image: "{{ registry }}/{{ project }}/{{ mig_ui_repo }}"
mig_ui_oauth_user_scope: "user:full"
mig_ui_oauth_redirect_url: ""
mig_ui_oauth_secret: ""
mig_ui_repo: "{{ lookup( 'env', 'MIG_UI_REPO') }}"
mig_ui_version: "{{ snapshot_tag | default(lookup( 'env', 'MIG_UI_TAG')) }}"
mig_ui_image_fqin: "{{ mig_ui_image }}:{{ mig_ui_version }}"
migration_registry_image: "{{ registry }}/{{ project }}/{{ migration_registry_repo }}"
migration_registry_repo: "{{ lookup( 'env', 'MIGRATION_REGISTRY_REPO') }}"
migration_registry_version: "{{ lookup( 'env', 'MIGRATION_REGISTRY_TAG') }}"
migration_registry_image_fqin: "{{ migration_registry_image }}:{{ migration_registry_version }}"
migration_stage_image: "{{ registry }}/{{ project }}/{{ velero_restic_restore_helper_repo }}"
migration_stage_repo: "{{ lookup( 'env', 'VELERO_RESTIC_RESTORE_HELPER_REPO') }}"
migration_stage_version: "{{ snapshot_tag | default(lookup( 'env', 'VELERO_RESTIC_RESTORE_HELPER_TAG')) }}"
migration_stage_image_fqin: "{{ migration_stage_image }}:{{ migration_stage_version }}"
olm_managed: false
registry: "{{ lookup( 'env', 'REGISTRY') }}"
project: "{{ lookup( 'env', 'PROJECT') }}"
restic_pv_host_path: /var/lib/kubelet/pods
restic_timeout: 1h
restic_supplemental_groups: []
ui_state: absent
velero_aws_secret_name: cloud-credentials
velero_gcp_secret_name: gcp-cloud-credentials
velero_azure_secret_name: azure-cloud-credentials
velero_debug: false
velero_image: "{{ registry }}/{{ project }}/{{ velero_repo }}"
velero_repo: "{{ lookup( 'env', 'VELERO_REPO') }}"
velero_version: "{{ snapshot_tag | default(lookup( 'env', 'VELERO_TAG')) }}"
velero_image_fqin: "{{ velero_image }}:{{ velero_version }}"
velero_plugin_image: "{{ registry }}/{{ project }}/{{ velero_plugin_repo }}"
velero_plugin_repo: "{{ lookup( 'env', 'VELERO_PLUGIN_REPO') }}"
velero_plugin_version: "{{ snapshot_tag | default(lookup( 'env', 'VELERO_PLUGIN_TAG')) }}"
velero_plugin_fqin: "{{ velero_plugin_image }}:{{ velero_plugin_version }}"
velero_restic_restore_helper_image: "{{ registry }}/{{ project }}/{{ velero_restic_restore_helper_repo }}"
velero_restic_restore_helper_repo: "{{ lookup( 'env', 'VELERO_RESTIC_RESTORE_HELPER_REPO') }}"
velero_restic_restore_helper_version: "{{ snapshot_tag | default(lookup( 'env', 'VELERO_RESTIC_RESTORE_HELPER_TAG')) }}"
velero_restic_restore_helper_fqin: "{{ velero_restic_restore_helper_image }}:{{ velero_restic_restore_helper_version }}"
velero_aws_plugin_image: "{{ registry }}/{{ project }}/{{ velero_aws_plugin_repo }}"
velero_aws_plugin_repo: "{{ lookup( 'env', 'VELERO_AWS_PLUGIN_REPO') }}"
velero_aws_plugin_version: "{{ snapshot_tag | default(lookup( 'env', 'VELERO_AWS_PLUGIN_TAG')) }}"
velero_aws_plugin_fqin: "{{ velero_aws_plugin_image }}:{{ velero_aws_plugin_version }}"
velero_gcp_plugin_image: "{{ registry }}/{{ project }}/{{ velero_gcp_plugin_repo }}"
velero_gcp_plugin_repo: "{{ lookup( 'env', 'VELERO_GCP_PLUGIN_REPO') }}"
velero_gcp_plugin_version: "{{ snapshot_tag | default(lookup( 'env', 'VELERO_GCP_PLUGIN_TAG')) }}"
velero_gcp_plugin_fqin: "{{ velero_gcp_plugin_image }}:{{ velero_gcp_plugin_version }}"
velero_azure_plugin_image: "{{ registry }}/{{ project }}/{{ velero_azure_plugin_repo }}"
velero_azure_plugin_repo: "{{ lookup( 'env', 'VELERO_AZURE_PLUGIN_REPO') }}"
velero_azure_plugin_version: "{{ snapshot_tag | default(lookup( 'env', 'VELERO_AZURE_PLUGIN_TAG')) }}"
velero_azure_plugin_fqin: "{{ velero_azure_plugin_image }}:{{ velero_azure_plugin_version }}"
velero_state: absent
velero_qps: 100
velero_burst: 1000

# MCG integration
noobaa: false
noobaa_expected_crds:
  - noobaas.noobaa.io
  - bucketclasses.noobaa.io
  - backingstores.noobaa.io
noobaa_admin_secret: noobaa-admin
noobaa_system_namespace: "{{ mig_namespace }}"
noobaa_mig_bucket_name: mig-storage
noobaa_s3_endpoint_proto: http
noobaa_system_core_cpu: 0.5
noobaa_system_core_mem: 500Mi
noobaa_system_db_cpu: 0.5
noobaa_system_db_mem: 1Gi
noobaa_system_endpoints_cpu: 1
noobaa_system_endpoints_mem: 500Mi
noobaa_system_endpoints_pod_count: 2
