---
configmap_secret: ""
controller_state: absent
deprecated_cors_configuration: false
image_pull_policy: Always
mig_controller_image: "{{ registry }}/{{ project }}/{{ mig_controller_repo }}"
mig_controller_limits_cpu: "100m"
mig_controller_limits_memory: "800Mi"
mig_controller_repo: "{{ lookup( 'env', 'MIG_CONTROLLER_REPO') }}"
mig_controller_requests_cpu: "100m"
mig_controller_requests_memory: "350Mi"
mig_controller_version: "{{ snapshot_tag | default(lookup( 'env', 'MIGRATION_TAG')) }}"
mig_namespace: openshift-migration
mig_svc_account: true
mig_ui_cluster_api_endpoint: ""
mig_ui_configmap_data: ""
mig_ui_configmap_name : mig-ui-config
mig_ui_config_namespace: openshift-config
mig_ui_image: "{{ registry }}/{{ project }}/{{ mig_ui_repo }}"
mig_ui_oauth_user_scope: "user:full"
mig_ui_oauth_redirect_url: ""
mig_ui_oauth_secret: ""
mig_ui_repo: "{{ lookup( 'env', 'MIG_UI_REPO') }}"
mig_ui_version: "{{ snapshot_tag | default(lookup( 'env', 'MIGRATION_TAG')) }}"
olm_managed: false
registry: "{{ lookup( 'env', 'REGISTRY') }}"
project: "{{ lookup( 'env', 'PROJECT') }}"
restic_pv_host_path: /var/lib/kubelet/pods
ui_state: absent
velero_aws_secret_name: cloud-credentials
velero_image: "{{ registry }}/{{ project }}/{{ velero_repo }}"
velero_repo: "{{ lookup( 'env', 'VELERO_REPO') }}"
velero_version: "{{ snapshot_tag | default(lookup( 'env', 'VELERO_TAG')) }}"
velero_plugin_image: "{{ registry }}/{{ project }}/{{ velero_plugin_repo }}"
velero_plugin_repo: "{{ lookup( 'env', 'VELERO_PLUGIN_REPO') }}"
velero_plugin_version: "{{ snapshot_tag | default(lookup( 'env', 'MIGRATION_TAG')) }}"
velero_restic_restore_helper_image: "{{ registry }}/{{ project }}/{{ velero_restic_restore_helper_repo }}"
velero_restic_restore_helper_repo: "{{ lookup( 'env', 'VELERO_RESTIC_RESTORE_HELPER_REPO') }}"
velero_restic_restore_helper_version: "{{ snapshot_tag | default(lookup( 'env', 'VELERO_TAG')) }}"
velero_state: absent
