apiVersion: apps/v1
kind: Deployment
metadata:
  name: migration-operator
  namespace: "openshift-migration"
  labels:
    app: migration
spec:
  selector:
    matchLabels:
      app: migration
  template:
    metadata:
      labels:
        app: migration
    spec:
      serviceAccountName: migration-operator
      containers:
      - name: operator
        image: quay.io/konveyor/mig-operator-container:release-1.5.1
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /tmp/ansible-operator/runner
          name: runner
        env:
        - name: OPERATOR_NAME
          value: migration-operator
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: REGISTRY
          value: quay.io
        - name: PROJECT
          value: konveyor
        - name: HOOK_RUNNER_REPO
          value: hook-runner
        - name: HOOK_RUNNER_TAG
          value: release-1.5.1
        - name: MIG_CONTROLLER_REPO
          value: mig-controller
        - name: MIG_UI_REPO
          value: mig-ui
        - name: MIGRATION_REGISTRY_REPO
          value: registry
        - name: MIGRATION_REGISTRY_TAG
          value: release-1.5.1
        - name: VELERO_REPO
          value: velero
        - name: VELERO_PLUGIN_REPO
          value: openshift-velero-plugin
        - name: VELERO_RESTIC_RESTORE_HELPER_REPO
          value: velero-restic-restore-helper
        - name: VELERO_AWS_PLUGIN_REPO
          value: velero-plugin-for-aws
        - name: VELERO_GCP_PLUGIN_REPO
          value: velero-plugin-for-gcp
        - name: VELERO_AZURE_PLUGIN_REPO
          value: velero-plugin-for-microsoft-azure
        - name: VELERO_TAG
          value: release-1.5.1
        - name: VELERO_RESTIC_RESTORE_HELPER_TAG
          value: release-1.5.1
        - name: VELERO_PLUGIN_TAG
          value: release-1.5.1
        - name: VELERO_AWS_PLUGIN_TAG
          value: release-1.5.1
        - name: VELERO_GCP_PLUGIN_TAG
          value: release-1.5.1
        - name: VELERO_AZURE_PLUGIN_TAG
          value: release-1.5.1
        - name: MIG_UI_TAG
          value: release-1.5.1
        - name: MIG_CONTROLLER_TAG
          value: release-1.5.1
      volumes:
        - name: runner
          emptyDir: {}
