- hosts: localhost
  gather_facts: false
  vars:
    QUAY_TOKEN: "{{ lookup( 'env', 'QUAY_TOKEN') | default('') }}"
  vars_prompt:
  - name: new_release
    prompt: "Last stable release"
    private: no
  tasks:
  - name: Add development bundle to the new index
    shell: |
           opm index add -c podman -f quay.io/konveyor/mig-operator-index:{{ new_release }} \
           --bundles quay.io/konveyor/mig-operator-bundle:latest \
           --tag quay.io/konveyor/mig-operator-index:latest

  - name: Push the complete index to latest
    shell: podman push quay.io/konveyor/mig-operator-index:latest

  - name: Make temp directory
    tempfile:
      state: directory
      suffix: catalog
    register: tmp_dir

  - name: Extract operator metadata
    shell: opm index export -c podman -i quay.io/konveyor/mig-operator-index:latest -o mtc-operator -f .
    args:
      chdir: "{{ tmp_dir.path }}"

  - name: Replace operator name
    replace:
      path: "{{ tmp_dir.path }}/mtc-operator/package.yaml"
      regexp: mtc-operator
      replace: crane-operator

  - name: Get current version
    uri:
      url: https://quay.io/cnr/api/v1/packages?namespace=konveyor
      return_content: yes
      headers:
        Authorization: "{{ QUAY_TOKEN }}"
    register: packages

  - name: Determine old app version
    set_fact:
      old_version: "{{ packages.json | selectattr('name', 'equalto', 'konveyor/crane-operator') | map(attribute='default') | list | first }}"

  - name: Set new app version
    set_fact:
      new_version: "{{ (old_version.split('.') | first | int)+1 }}.0.0"

  - name: Push App
    shell: operator-courier --verbose push . konveyor crane-operator {{ new_version }} "$QUAY_TOKEN".
    args:
      chdir: "{{ tmp_dir.path }}/crane-operator"

