- hosts: localhost
  vars:
    org: konveyor
    repos1:
    - mig-operator
    - mig-controller
    - mig-ui
    - must-gather
    - hook-runner
    repos2:
    - openshift-velero-plugin
    - distribution
    - mig-log-reader
    - rsync-transfer
    crane_repos:
    - velero
    - velero-plugin-for-gcp
    - velero-plugin-for-aws
    - velero-plugin-for-microsoft-azure
    - restic
    gh_token: "{{ lookup( 'env', 'GH_TOKEN') }}"
  vars_prompt:
  - name: sprint
    prompt: "Sprint number"
    private: no

  - name: release
    prompt: "Release attempt"
    private: no
  tasks:
  - name: Get current master SHAs for first set
    uri:
      url: https://api.github.com/repos/{{ org }}/{{ item }}/git/refs/heads/master
      method: GET
      headers:
        Authorization: token {{ gh_token }}
    register: repo_info1
    with_items: "{{ repos1 }}"

  - name: Get current master SHAs for second set
    uri:
      url: https://api.github.com/repos/{{ org }}/{{ item }}/git/refs/heads/master
      method: GET
      headers:
        Authorization: token {{ gh_token }}
    register: repo_info2
    with_items: "{{ repos2 }}"

  - name: Get current konveyor-dev SHAs
    uri:
      url: https://api.github.com/repos/{{ org }}/{{ item }}/git/refs/heads/konveyor-dev
      method: GET
      headers:
        Authorization: token {{ gh_token }}
    register: crane_repo_info
    with_items: "{{ crane_repos }}"

  - name: Create sprint branches from master for repo set 1
    uri:
      url: https://api.github.com/repos/{{ org }}/{{ item.item }}/git/refs
      body: '{ "ref": "refs/heads/sprint-{{ sprint }}.{{ release }}", "sha": "{{ item.json.object.sha }}"  }'
      body_format: json
      method: POST
      headers:
        Authorization: token {{ gh_token }}
        Content-Type: application/json
      status_code: 201
    register:
    with_items: "{{ repo_info1.results }}"
    loop_control:
      label: "repo: {{ item.item }}, sha: {{ item.json.object.sha }}, tag: sprint-{{ sprint }}.{{ release }}"

  - name: Pause to split requests so we don't exceed Quay's maximum build rate and get 429's
    pause:
      minutes: 5

  - name: Create sprint branches from master for repo set 2
    uri:
      url: https://api.github.com/repos/{{ org }}/{{ item.item }}/git/refs
      body: '{ "ref": "refs/heads/sprint-{{ sprint }}.{{ release }}", "sha": "{{ item.json.object.sha }}"  }'
      body_format: json
      method: POST
      headers:
        Authorization: token {{ gh_token }}
        Content-Type: application/json
      status_code: 201
    register:
    with_items: "{{ repo_info2.results }}"
    loop_control:
      label: "repo: {{ item.item }}, sha: {{ item.json.object.sha }}, tag: sprint-{{ sprint }}.{{ release }}"

  - name: Pause to split requests so we don't exceed Quay's maximum build rate and get 429's
    pause:
      minutes: 5

  - name: Create sprint branches from konveyor-dev
    uri:
      url: https://api.github.com/repos/{{ org }}/{{ item.item }}/git/refs
      body: '{ "ref": "refs/heads/sprint-{{ sprint }}.{{ release }}", "sha": "{{ item.json.object.sha }}"  }'
      body_format: json
      method: POST
      headers:
        Authorization: token {{ gh_token }}
        Content-Type: application/json
      status_code: 201
    register:
    with_items: "{{ crane_repo_info.results }}"
    loop_control:
      label: "repo: {{ item.item }}, sha: {{ item.json.object.sha }}, tag: sprint-{{ sprint }}.{{ release }}"

  - name: Make temp directory
    tempfile:
      state: directory
      suffix: "sprint-{{ sprint }}.{{ release }}"
    register: tmp_dir

  - name: Clone mig-operator
    git:
      repo: https://github.com/konveyor/mig-operator.git
      dest: "{{ tmp_dir.path }}/mig-operator"
      version: bundle

  - name: Replace operator tags in CSV
    replace:
      path:  "{{ tmp_dir.path }}/mig-operator/deploy/olm-catalog/bundle/manifests/crane-operator.v99.0.0.clusterserviceversion.yaml"
      regexp: ':latest'
      replace: ":sprint-{{ sprint }}.{{ release }}"

  - name: Replace operand in CSV
    replace:
      path:  "{{ tmp_dir.path }}/mig-operator/deploy/olm-catalog/bundle/manifests/crane-operator.v99.0.0.clusterserviceversion.yaml"
      regexp: 'value: latest'
      replace: "value: sprint-{{ sprint }}.{{ release }}"

  - name: Build bundle
    shell: podman build -f build/Dockerfile.bundle -t quay.io/konveyor/mig-operator-bundle:sprint-{{ sprint }}.{{ release }} .
    args:
      chdir: "{{ tmp_dir.path }}/mig-operator"

  - name: Push bundle
    shell: podman push quay.io/konveyor/mig-operator-bundle:sprint-{{ sprint }}.{{ release }}

  - name: Build sprint index image
    shell: opm index add -p docker --bundles quay.io/konveyor/mig-operator-bundle:sprint-{{ sprint }}.{{ release }} --tag quay.io/konveyor/mig-operator-index:sprint-{{ sprint }}.{{ release }}

  - name: Push sprint index image
    shell: podman push quay.io/konveyor/mig-operator-index:sprint-{{ sprint }}.{{ release }}
