#! parse-kind: ClusterServiceVersion
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: mig-operator.0.0.1
  namespace: placeholder
  annotations:
    capabilities: Seamless Upgrades
    description: Facilitates migration of workloads from Openshift 3.x to Openshift 4.x
    categories: 'OpenShift Optional'
    containerImage: quay.io/ocpmigrate/mig-operator:v0.0.10
    createdAt: 2019-07-25T10:21:00Z
    repository: https://github.com/fusor/mig-operator
    alm-examples: '[{"apiVersion":"migration.openshift.io/v1alpha1","kind":"MigrationController","metadata":{"name":"migration-controller","namespace":"mig"},"spec":{"cluster_name":"host","migration_velero":true,"migration_controller":true,"migration_ui":true}},{"apiVersion":"velero.io/v1","kind":"Backup","metadata":{"name":"backup","namespace":"mig"},"spec":{}},{"apiVersion":"velero.io/v1","kind":"BackupStorageLocation","metadata":{"name":"backupstoragelocation","namespace":"mig"},"spec":{}},{"apiVersion":"velero.io/v1","kind":"DeleteBackupRequest","metadata":{"name":"deletebackuprequest","namespace":"mig"},"spec":{}},{"apiVersion":"velero.io/v1","kind":"DownloadRequest","metadata":{"name":"downloadrequest","namespace":"mig"},"spec":{}},{"apiVersion":"velero.io/v1","kind":"PodVolumeBackup","metadata":{"name":"podvolumebackup","namespace":"mig"},"spec":{}},{"apiVersion":"velero.io/v1","kind":"PodVolumeRestore","metadata":{"name":"podvolumerestore","namespace":"mig"},"spec":{}},{"apiVersion":"velero.io/v1","kind":"ResticRepository","metadata":{"name":"resticrepository","namespace":"mig"},"spec":{}},{"apiVersion":"velero.io/v1","kind":"Restore","metadata":{"name":"restore","namespace":"mig"},"spec":{}},{"apiVersion":"velero.io/v1","kind":"Schedule","metadata":{"name":"schedule","namespace":"mig"},"spec":{}},{"apiVersion":"velero.io/v1","kind":"ServerStatusRequest","metadata":{"name":"serverstatusrequest","namespace":"mig"},"spec":{}},{"apiVersion":"velero.io/v1","kind":"VolumeSnapshotLocation","metadata":{"name":"volumesnapshotlocation","namespace":"mig"},"spec":{}},{"apiVersion":"clusterregistry.k8s.io/v1alpha1","kind":"Cluster","metadata":{"name":"cluster","namespace":"mig"},"spec":{}},{"apiVersion":"migration.openshift.io/v1alpha1","kind":"MigCluster","metadata":{"name":"host","namespace":"mig"},"spec":{}},{"apiVersion":"migration.openshift.io/v1alpha1","kind":"MigPlan","metadata":{"name":"migplan","namespace":"mig"},"spec":{}},{"apiVersion":"migration.openshift.io/v1alpha1","kind":"MigMigration","metadata":{"name":"migmigration","namespace":"mig"},"spec":{}},{"apiVersion":"migration.openshift.io/v1alpha1","kind":"MigStorage","metadata":{"name":"migstorage","namespace":"mig"},"spec":{}}]'
    certified: "false"
    support: Jason Montleon
spec:
  displayName: Migration Operator
  description: |
    The Migration Operator for Openshift enables installation of the Openshift 3.x to Openshift 4.x solution.
  keywords: ['migration']

  maintainers:
  - name: Red Hat
    email: openshift-operators@redhat.com

  provider:
    name: Red Hat

  links:
  - name: Migrations
    url: https://github.com/fusor/mig-controller
  - name: Documentation
    url: https://github.com/fusor/mig-operator
  - name: Migration Operator
    url: https://github.com/fusor/mig-operator

  labels:
    alm-status-descriptors: mig-operator.0.0.1
    alm-owner-prometheus: mig-operator

  selector:
    matchLabels:
      alm-owner-prometheus: mig-operator

  icon:
  - base64data: PHN2ZyBpZD0iTGF5ZXJfMSIgZGF0YS1uYW1lPSJMYXllciAxIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxOTIgMTQ1Ij48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6I2UwMDt9PC9zdHlsZT48L2RlZnM+PHRpdGxlPlJlZEhhdC1Mb2dvLUhhdC1Db2xvcjwvdGl0bGU+PHBhdGggZD0iTTE1Ny43Nyw2Mi42MWExNCwxNCwwLDAsMSwuMzEsMy40MmMwLDE0Ljg4LTE4LjEsMTcuNDYtMzAuNjEsMTcuNDZDNzguODMsODMuNDksNDIuNTMsNTMuMjYsNDIuNTMsNDRhNi40Myw2LjQzLDAsMCwxLC4yMi0xLjk0bC0zLjY2LDkuMDZhMTguNDUsMTguNDUsMCwwLDAtMS41MSw3LjMzYzAsMTguMTEsNDEsNDUuNDgsODcuNzQsNDUuNDgsMjAuNjksMCwzNi40My03Ljc2LDM2LjQzLTIxLjc3LDAtMS4wOCwwLTEuOTQtMS43My0xMC4xM1oiLz48cGF0aCBjbGFzcz0iY2xzLTEiIGQ9Ik0xMjcuNDcsODMuNDljMTIuNTEsMCwzMC42MS0yLjU4LDMwLjYxLTE3LjQ2YTE0LDE0LDAsMCwwLS4zMS0zLjQybC03LjQ1LTMyLjM2Yy0xLjcyLTcuMTItMy4yMy0xMC4zNS0xNS43My0xNi42QzEyNC44OSw4LjY5LDEwMy43Ni41LDk3LjUxLjUsOTEuNjkuNSw5MCw4LDgzLjA2LDhjLTYuNjgsMC0xMS42NC01LjYtMTcuODktNS42LTYsMC05LjkxLDQuMDktMTIuOTMsMTIuNSwwLDAtOC40MSwyMy43Mi05LjQ5LDI3LjE2QTYuNDMsNi40MywwLDAsMCw0Mi41Myw0NGMwLDkuMjIsMzYuMywzOS40NSw4NC45NCwzOS40NU0xNjAsNzIuMDdjMS43Myw4LjE5LDEuNzMsOS4wNSwxLjczLDEwLjEzLDAsMTQtMTUuNzQsMjEuNzctMzYuNDMsMjEuNzdDNzguNTQsMTA0LDM3LjU4LDc2LjYsMzcuNTgsNTguNDlhMTguNDUsMTguNDUsMCwwLDEsMS41MS03LjMzQzIyLjI3LDUyLC41LDU1LC41LDc0LjIyYzAsMzEuNDgsNzQuNTksNzAuMjgsMTMzLjY1LDcwLjI4LDQ1LjI4LDAsNTYuNy0yMC40OCw1Ni43LTM2LjY1LDAtMTIuNzItMTEtMjcuMTYtMzAuODMtMzUuNzgiLz48L3N2Zz4=
    mediatype: image/svg+xml

  installModes:
  - type: OwnNamespace
    supported: true
  - type: SingleNamespace
    supported: true
  - type: MultiNamespace
    supported: true
  - type: AllNamespaces
    supported: false

  install:
    strategy: deployment
    spec:
      permissions:
      - serviceAccountName: migration-operator
        rules:
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - migration-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - migration.openshift.io
          resources:
          - '*'
          verbs:
          - '*'
      clusterPermissions:
      - serviceAccountName: migration-operator
        rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          - namespaces
          verbs:
          - get
          - list
        - apiGroups:
          - oauth.openshift.io
          resources:
          - oauthclients
          verbs:
          - '*'
        - apiGroups:
          - operator.openshift.io
          resources:
          - kubeapiservers
          - authentications
          verbs:
          - '*'
      - serviceAccountName: migration-controller
        rules:
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - namespaces/status
          verbs:
          - get
          - update
          - patch
        - apiGroups:
          - migration.openshift.io
          resources:
          - migclusters
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - migration.openshift.io
          resources:
          - migclusters/status
          verbs:
          - get
          - update
          - patch
        - apiGroups:
          - apps
          resources:
          - '*'
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - clusterregistry.k8s.io
          resources:
          - clusters
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - clusterregistry.k8s.io
          resources:
          - clusters/status
          verbs:
          - get
          - update
          - patch
        - apiGroups:
          - migration.openshift.io
          resources:
          - migmigrations
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - migration.openshift.io
          resources:
          - migmigrations/status
          verbs:
          - get
          - update
          - patch
        - apiGroups:
          - migration.openshift.io
          resources:
          - migplans
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - migration.openshift.io
          resources:
          - migplans/status
          verbs:
          - get
          - update
          - patch
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - pods/status
          verbs:
          - get
          - update
          - patch
        - apiGroups:
          - ""
          resources:
          - persistentvolumes
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - persistentvolumes/status
          verbs:
          - get
          - update
          - patch
        - apiGroups:
          - ""
          resources:
          - persistentvolumeclaims
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - persistentvolumeclaims/status
          verbs:
          - get
          - update
          - patch
        - apiGroups:
          - migration.openshift.io
          resources:
          - migstages
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - migration.openshift.io
          resources:
          - migstages/status
          verbs:
          - get
          - update
          - patch
        - apiGroups:
          - migration.openshift.io
          resources:
          - migstorages
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - migration.openshift.io
          resources:
          - migstorages/status
          verbs:
          - get
          - update
          - patch
        - apiGroups:
          - velero.io
          resources:
          - '*'
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - image.openshift.io
          resources:
          - '*'
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - apps.openshift.io
          resources:
          - '*'
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - admissionregistration.k8s.io
          resources:
          - mutatingwebhookconfigurations
          - validatingwebhookconfigurations
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - services
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - storage.k8s.io
          resources:
          - storageclasses
          verbs:
          - get
          - list
          - watch
      - serviceAccountName: mig
        rules:
        - apiGroups:
          - '*'
          resources:
          - '*'
          verbs:
          - '*'
        - nonResourceURLs:
          - '*'
          verbs:
          - '*'
      - serviceAccountName: velero
        rules:
        - apiGroups:
          - '*'
          resources:
          - '*'
          verbs:
          - '*'
        - nonResourceURLs:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - security.openshift.io"
          resources:
          - securitycontextconstraints
          verbs:
          - use
          resourceNames:
          - privileged
      deployments:
      - name: migration-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: migration-operator
          template:
            metadata:
              labels:
                app: migration-operator
            spec:
              serviceAccount: migration-operator
              containers:
              - name: ansible
                image: quay.io/ocpmigrate/mig-operator:olm
                command:
                - /usr/local/bin/ao-logs
                - /tmp/ansible-operator/runner
                - stdout
                imagePullPolicy: Always
                volumeMounts:
                - mountPath: /tmp/ansible-operator/runner
                  name: runner
                  readOnly: true
              - name: operator
                image: quay.io/ocpmigrate/mig-operator:olm
                imagePullPolicy: Always
                volumeMounts:
                - mountPath: /tmp/ansible-operator/runner
                  name: runner
                env:
                - name: OPERATOR_NAME
                  value: migration-operator
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
              volumes:
              - name: runner
                emptyDir: {}
  maturity: alpha
  version: 0.0.1
  customresourcedefinitions:
    owned:
    - name: backupstoragelocations.velero.io
      version: v1
      kind: BackupStorageLocation
      displayName: BackupStorageLocation
      description: A velero backup storage location
    - name: backups.velero.io
      version: v1
      kind: Backup
      displayName: Backup
      description: A velero backup
    - name: clusters.clusterregistry.k8s.io
      version: v1alpha1
      kind: Cluster
      displayName: Cluster
      description: A k8s cluster
    - name: deletebackuprequests.velero.io
      version: v1
      kind: DeleteBackupRequest
      displayName: DeleteBackupRequest
      description: A request to delete a velero backup
    - name: downloadrequests.velero.io
      version: v1
      kind: DownloadRequest
      displayName: DownloadRequest
      description: A download request for velero
    - name: migclusters.migration.openshift.io
      version: v1alpha1
      kind: MigCluster
      displayName: MigCluster
      description: A cluster defined for migration
    - name: migmigrations.migration.openshift.io
      version: v1alpha1
      kind: MigMigration
      displayName: MigMigration
      description: A migration process
    - name: migplans.migration.openshift.io
      version: v1alpha1
      kind: MigPlan
      displayName: MigPlan
      description: A migration plan
    - name: migrationcontrollers.migration.openshift.io
      version: v1alpha1
      kind: MigrationController
      displayName: MigrationController
      description: A migration contoller deployment
      resources:
      - kind: MigCluster
        version: migration.openshift.io/v1alpha1
      - kind: Secret
        version: v1
      - kind: Service
        version: v1
      - kind: Deployment
        version: apps/v1
      - kind: Configmap
        version: v1
      - kind: OAuthClient
        version: oauth.openshift.io/v1
      - kind: Route
        version: route.openshift.io/v1
      - kind: Daemonset
        version: apps/v1
    - name: migstorages.migration.openshift.io
      version: v1alpha1
      kind: MigStorage
      displayName: MigStorage
      description: A migration storage location
    - name: podvolumebackups.velero.io
      version: v1
      kind: PodVolumeBackup
      displayName: PodVolumeBackup
      description: A velero pod volume backup
    - name: podvolumerestores.velero.io
      version: v1
      kind: PodVolumeRestore
      displayName: PodVolumeRestore
      description: A velero pod volume restore
    - name: resticrepositories.velero.io
      version: v1
      kind: ResticRepository
      displayName: ResticRepository
      description: A restic repository for velero
    - name: restores.velero.io
      version: v1
      kind: Restore
      displayName: Restore
      description: A velero restore
    - name: schedules.velero.io
      version: v1
      kind: Schedule
      displayName: Schedule
      description: A velero schedule
    - name: serverstatusrequests.velero.io
      version: v1
      kind: ServerStatusRequest
      displayName: ServerStatusRequest
      description: A velero server status request
    - name: volumesnapshotlocations.velero.io
      version: v1
      kind: VolumeSnapshotLocation
      displayName: VolumeSnapshotLocation
      description: A velero volume snapshot location
