---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/node-selector: ""
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
    openshift.io/cluster-monitoring: "true"
  name: "openshift-migration"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  annotations:
    openshift.io/description: Allows deploymentconfigs in this namespace to rollout
      pods in this namespace.  It is auto-managed by a controller; remove subjects
      to disable.
  name: system:deployers
  namespace: openshift-migration
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:deployer
subjects:
- kind: ServiceAccount
  name: deployer
  namespace: openshift-migration
userNames:
- system:serviceaccount:openshift-migration:deployer
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  annotations:
    openshift.io/description: Allows builds in this namespace to push images to this
      namespace.  It is auto-managed by a controller; remove subjects to disable.
  name: system:image-builders
  namespace: openshift-migration
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-builder
subjects:
- kind: ServiceAccount
  name: builder
  namespace: openshift-migration
userNames:
- system:serviceaccount:openshift-migration:builder
---
apiVersion: rbac.authorization.k8s.io/v1beta1
groupNames:
- system:serviceaccounts:openshift-migration
kind: RoleBinding
metadata:
  annotations:
    openshift.io/description: Allows all pods in this namespace to pull images from
      this namespace.  It is auto-managed by a controller; remove subjects to disable.
  creationTimestamp: null
  name: system:image-pullers
  namespace: openshift-migration
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-puller
subjects:
- kind: Group
  name: system:serviceaccounts:openshift-migration
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: migration-operator
  namespace: "openshift-migration"
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: migrationcontrollers.migration.openshift.io
spec:
  group: migration.openshift.io
  names:
    kind: MigrationController
    listKind: MigrationControllerList
    plural: migrationcontrollers
    singular: migrationcontroller
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: migrationtenants.migration.openshift.io
spec:
  group: migration.openshift.io
  names:
    kind: MigrationTenant
    listKind: MigrationTenants
    plural: migrationtenants
    singular: migrationtenant
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  creationTimestamp: null
  name: migration-operator
  namespace: "openshift-migration"
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - mig-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - migration.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: migration-operator
  namespace: "openshift-migration"
subjects:
- kind: ServiceAccount
  name: migration-operator
roleRef:
  kind: Role
  name: migration-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: migration-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: migration-operator
    namespace: "openshift-migration"
namespace: "openshift-migration"
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: migration-operator
  namespace: "openshift-migration"
  labels:
    app: migration
spec:
  selector:
    matchLabels:
      app: migration
  template:
    metadata:
      labels:
        app: migration
    spec:
      serviceAccountName: migration-operator
      containers:
      - name: ansible
        command:
        - /usr/local/bin/ao-logs
        - /tmp/ansible-operator/runner
        - stdout
        image: quay.io/konveyor/mig-operator-container:non-admin
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /tmp/ansible-operator/runner
          name: runner
          readOnly: true
      - name: operator
        image: quay.io/konveyor/mig-operator-container:non-admin
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /tmp/ansible-operator/runner
          name: runner
        env:
        - name: OPERATOR_NAME
          value: migration-operator
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: REGISTRY
          value: quay.io
        - name: PROJECT
          value: konveyor
        - name: MIG_CONTROLLER_REPO
          value: mig-controller
        - name: MIG_UI_REPO
          value: mig-ui
        - name: MIGRATION_REGISTRY_REPO
          value: registry
        - name: MIGRATION_REGISTRY_TAG
          value: latest
        - name: VELERO_REPO
          value: velero
        - name: VELERO_PLUGIN_REPO
          value: migration-plugin
        - name: VELERO_RESTIC_RESTORE_HELPER_REPO
          value: velero-restic-restore-helper
        - name: VELERO_AWS_PLUGIN_REPO
          value: velero-plugin-for-aws
        - name: VELERO_GCP_PLUGIN_REPO
          value: velero-plugin-for-gcp
        - name: VELERO_AZURE_PLUGIN_REPO
          value: velero-plugin-for-microsoft-azure
        - name: VELERO_TAG
          value: latest
        - name: VELERO_RESTIC_RESTORE_HELPER_TAG
          value: latest
        - name: VELERO_PLUGIN_TAG
          value: latest
        - name: VELERO_AWS_PLUGIN_TAG
          value: latest
        - name: VELERO_GCP_PLUGIN_TAG
          value: latest
        - name: VELERO_AZURE_PLUGIN_TAG
          value: latest
        - name: MIG_UI_TAG
          value: latest
        - name: MIG_CONTROLLER_TAG
          value: latest
      volumes:
        - name: runner
          emptyDir: {}
